### ISSUE TITLE
psql-app can't create tables in Postgres

### ISSUE THREAD

**Issue by untrustedworld** [OpenBMP/obmp-docker#6]
Hi,

I faced with a problem when psql-app can't create tables in Postgres.
Looks like it is not possible to create tables, because the relations does not exist.

I'm using the lastest versions of docker containters from docker hub.

There are also lots of errors in grafana:
`
db query error: pq: relation "stats_ip_origins" does not exist

db query error: pq: relation "stats_peer_rib" does not exist

db query error: pq: invalid input syntax for type uuid: ""

db query error: pq: relation "stats_chg_byasn" does not exist

db query error: pq: relation "v_ip_routes_history" does not exist

etc.
`
Postgres error log will be in attachement.
Please help to solve the issue!
[psql-app_error.txt](https://github.com/OpenBMP/obmp-docker/files/7066326/psql-app_error.txt)

**Comment by TimEvens** [comment]
The error ```ERROR:  tablespace "timeseries" does not exist``` suggests a problem with the ```obmp-psql``` container. There was an error a while back with that container that didn't create the tablespace. That has been fixed in build-56 of the container. 

I will be updating the tags to include a version instead of build numbers in the next few days.  I am also updating the compose to use a specific version instead of ```latest```.    I'll update this issue in the next few days when I have the new containers and tags done.

**Comment by BouchardClaude** [comment]
maybe related to issue #11  I just created as it is the same behaviour if I understand it correctly
